"""empty message

Revision ID: d83552304d56
Revises: ae96149a3f7b
Create Date: 2020-05-13 20:11:16.256467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83552304d56'
down_revision = 'ae96149a3f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'genres')
    op.add_column('venue', sa.Column('seeking_talent_description', sa.String(), nullable=True))
    op.drop_column('venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_talent_description')
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
